### PR TITLE
Object initialization shortcuts

### PR DESCRIPTION
**Pull request by al6x**
A shorter way to pass parameters during object initalization, read [rendered markdown](https://github.com/al6x/RFCs/blob/master/RFCs/Object_Initialization_Shortcuts.md)

Short example:

```Nim
type
  Unit = object
    race: string
    hp:   int
    name: string

let
  race = "Protoss"
  hp   = 100
echo Unit(race, hp, name: "Zeratul")
echo Unit(race, hp, name: "Artanis")

echo Unit(:race, :hp, name: "Zeratul") # Alternative way
```

CC @dom96

### CODE REVIEW

**Comment by mratsim** [comment]
The syntax is ambiguous regarding the let scope. This is better

```Nim
type
  Unit = object
    race: string
    hp:   int
    name: string

with(Unit):
  race = "Protoss"
  hp   = 100
  echo Unit(race, hp, name: "Zeratul")
  echo Unit(race, hp, name: "Artanis")

  echo Unit(:race, :hp, name: "Zeratul") # Alternative way
```

So that the default value are scoped.

Alternatively we can expand ``using`` which currently supports

```Nim
using
  c: Context
  n: Node
  counter: int

proc foo(c, n) = ...
proc bar(c, n, counter) = ...
proc baz(c, n) = ...

proc mixedMode(c, n; x, y: int) =
  # 'c' is inferred to be of the type 'Context'
  # 'n' is inferred to be of the type 'Node'
  # But 'x' and 'y' are of type 'int'.
```

**Comment by al6x** [comment]
Hmm, `with` and `using` feels too complicated, the whole point of this shortcut is to be trivial and be used on the fly. 

The need to know about and use special keywords like `with` or `using` kinda defeat the whole point of having such shortcut. In the end code will be even more complicated than without using it at all.

**Comment by mratsim** [comment]
I think the only thing needed is to have object constructor not require the field names just like a proc call.

i.e. today we have to do `MyConstructor(a: x, b: y, c: z)` and we should allow `MyConstructor(x, y, z)`

**Comment by bluenote10** [comment]
> I think the only thing needed is to have object constructor not require the field names just like a proc call.

Wouldn't that imply that changing the order of the fields in the type definition is a breaking change?

Rust also has this shorthand that the field name can be omitted if and only if the local variable has the same name, which in my opinion is a nice tradeoff in terms of conciseness and safe semantics.

**Comment by mratsim** [comment]
> > I think the only thing needed is to have object constructor not require the field names just like a proc call.
> 
> Wouldn't that imply that changing the order of the fields in the type definition is a breaking change?

Yes but I think this pattern is common

```Nim
type Foo = object
  a: int
  b: float
  c: string

proc initFoo(a: int, b: float, c: string): Foo =
  result.a = a
  result.b = b
  result.c = c

let
  a = 1
  b = 2.0
  c = "three"

let x = initFoo(a, b, c)
```
or
```Nim
type Foo = object
  a: int
  b: float
  c: string

let
  a = 1
  b = 2.0
  c = "three"
let x = Foo(a: a, b: b, c: c) 
```

and both would be replaced by
```Nim
type Foo = object
  a: int
  b: float
  c: string

let
  a = 1
  b = 2.0
  c = "three"
let x = Foo(a, b, c) 
```

**Comment by timotheecour** [comment]
This can and should be done via a macro instead of compiler patch.
```nim
echo Unit.init(race, hp, name: "Zeratul")
```

**Comment by timotheecour** [comment]
closing, see https://github.com/nim-lang/RFCs/pull/225; please re-open as an issue, not a PR

**Pull request closed without merging**
