### PR TITLE
Create Dart_Backend

### PR DESCRIPTION
**Pull request by jfilby**
An RFC for the creation of a Dart backend.

### CODE REVIEW

**Comment by nc-x** [comment]
Hi @jfilby
Creating a new backend is a huge task, and requires lots of time to be implemented. And even if a dart backend is implemented, there is a very high chance that the Nim semantics do not match exactly to Dart (If you have ever used Haxe, you will know that while having various backends sounds good, but it always leaves much to be desired).
Also a Dart backend does not mean that it will be easy to use Flutter. Flutter has a huge surface area which would still need to be somehow wrapped, which again due to differences between Nim and Dart might be a big headache.
Anyways, the time it would take to implement and maintain a Dart backend itself suggests against implementing it. If there are developers willing to work on the Nim compiler, they should preferably help with finishing/polishing the features, improving the tooling and modernizing the stdlib.

Also, no need to create a PR in the future for an RFCs. We use issues themselves for the RFCs. :)

**Comment by Araq** [comment]
As an RFC it's fine, yes it's much work but maybe we find an easier solution during the discussion.

**Comment by juancarlospaco** [comment]
- Nim :arrow_right: Node https://github.com/juancarlospaco/nodejs#documentation
- Node :arrow_right: Mobile https://android-js.github.io
- Node (WASM, HTTPS2.0 Server, etc) ↔️ Nim (Karax, Fidget, NimX, etc).

**Comment by dom96** [comment]
> As an RFC it's fine

I disagree, this isn't what we should be encouraging. This is far from what an RFC should be: a detailed account of the suggestion, with discussions around the problems that it solves. This is fine for our forum, but this repo should have a higher standard IMO.

**Comment by jfilby** [comment]
When I try to create a new Issue and click New Feature, the top of the text preset says to create an RFC for large features.

Regarding not enough detail, that would require a much more in-depth knowledge of the Nim compiler than I have. If there is not much support for this RFC then it can be closed.

**Comment by Yardanico** [comment]
@jfilby 
> When I try to create a new Issue and click New Feature, the top of the text preset says to create an RFC for large features.

You misunderstood a bit - you should create an RFC as an issue in this RFCs repo (check other issues, they're all RFCs), not in the Nim repo

**Comment by Araq** [comment]
> I disagree, this isn't what we should be encouraging. This is far from what an RFC should be: a detailed account of the suggestion, with discussions around the problems that it solves. This is fine for our forum, but this repo should have a higher standard IMO.

Alright, I take it back.

**Comment by jfilby** [comment]
Could I repost this as an issue (feature) for further investigation at a
later stage?

Thanks
Jason

**Comment by Araq** [comment]
Please write a forum post first.

**Comment by jfilby** [comment]
Here's the original thread: https://forum.nim-lang.org/t/8005

The idea started with transpiling Nim to Dart, but the conversation changed
to a Dart backend for Nim.

Would you prefer a new thread?

**Pull request closed without merging**
