### PR TITLE
Added async/chronos rfc

### PR DESCRIPTION
**Pull request by zevv**

### CODE REVIEW

**Comment by GULPF** [comment]
> Should the Nim stdlib drop the current implementation in favour of Chronos?

Does this mean "integrate Chronos into the stdlib" or "no async implementation in the stdib"?

**Comment by cheatfate** [comment]
@zevv there not just 2 async implementations present, you forgot to mention https://github.com/zielmicha/reactor.nim and it present since  Dec 28, 2015, there also present one more but i do not exactly remember its name.

**Comment by cheatfate** [comment]
Also it would be nice to add one more variant to possible ways:
- Transfer `asyncdispatch.nim` and friends to packages (e.g. asyncdispatch, asynchttpserver, asynchttpclient and so on).

In such way every new asynchronous framework will get equal rights and possibilities and competition between developers will get for much more polished asynchronous framework.

**Comment by mratsim** [comment]
As was mentionned by Araq on IRC on the discussion Nim batteries-included, raw Nim and Nim "rocket-included" in some cases people can only use what is provided by Nim and the standard library.

However I do agree that if we plan to have a better Nim the standard library should be top notch and ways for that could be:

- facilitate replacing packages in the standard library (https://github.com/zevv/nim-async-issue/issues/2)
- radically switch to a pure OS abstraction + abstract interfaces/concepts standard library so that alternative implementation can compete and library users only have to implement the interfaces, this raises the question "What is the vision for Nim standard library" (https://github.com/zevv/nim-async-issue/issues/3)

Those questions should probably be as separate RFCs though.

**Pull request merged**
