### PR TITLE
jsgen improved infra RFC

### PR DESCRIPTION
**Pull request by kristianmandrup**
See [PR #13381](https://github.com/nim-lang/Nim/pull/13381)

This RFC has a much better description and of the proposed `jsgen` infrastructure improvements with examples for what would be possible using these new building blocks.

This new infrastructure would support:
- ECMA Script modules imports/exports
- ECMA Script classes
- Decorators (experimental) for class, method and properties
- TypeScript interop
- NodeJS with ES modules
- deno
- ...

### CODE REVIEW

**Comment by Araq** [comment]
Please submit the same markdown document as an "Issue" to this repository.

**Comment by kristianmandrup** [comment]
I assume you mean as a Feature proposal issue:

https://github.com/nim-lang/Nim/issues/new?assignees=&labels=&template=feature_request.md&title=

I will follow this template

**Comment by alehander92** [comment]
Please just paste the document again but as an issue like https://github.com/nim-lang/RFCs/issues/191 etc

**Comment by kristianmandrup** [comment]
Please review. Used the issue:feature template and divided into smaller feature proposals, much easier to follow and understand, without any reference too implementation details

**Comment by zedeus** [comment]
Create an issue, not a pull request.

**Comment by timotheecour** [comment]
> Create an issue, not a pull request.

indeed; closing, see https://github.com/nim-lang/RFCs/pull/225; please re-open as an issue

**Pull request closed without merging**
